name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3

      - name: Navigate to Flutter project
        run: cd ctww

      - name: Install dependencies
        run: |
          cd ctww
          flutter pub get

      - name: Build Flutter Web
        run: |
          cd ctww
          flutter build web --release

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: riley
          folder: ctww/build/web